server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: microservice-talk
  cloud:
    function:
      autodetect: false
    stream:
      function:
        autodetect: false
        definition: "memberEvents"
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:19092}
          configuration:
            schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        bindings:
          talkEvents-in-0:
            consumer:
              enableDlq: true
              dlqName: talk.dlq
          memberEvents-in-0:
            consumer:
              enableDlq: true
              dlqName: member.dlq
      bindings:
        talkEvents-out-0:
          destination: talk
          content-type: application/*+avro
        talkEvents-in-0:
          destination: talk
          group: ${spring.application.name}-group
          content-type: application/*+avro
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
            back-off-multiplier: 2.0
        memberEvents-in-0:
          destination: member
          group: ${spring.application.name}-group
          content-type: application/*+avro
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
            back-off-multiplier: 2.0

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rdb-microservice-talk}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    baseline-on-migrate: true
