server:
  port: 8082

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/microservice-talk
    username: postgres
    password: postgres
