server:
  port: 8083

spring:
  application:
    name: microservice-talk
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: microservice-talk
        instance-id: ${spring.application.name}:${server.port}
